codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "95...100"

  status:
    project:
      target: auto
      default: on
    patch:
      target: auto
      default: on

comment:
  layout: "header,diff,files,footer"
  behavior: default
  require_changes: no

ignore:
  - "tests/*.js"
